### ISSUE TITLE
Client: Missing "navigation" component 

### ISSUE THREAD

**Issue by k7k0** [DNACodeStudios/react-rails-bootstrap#1]
This `client/src/shared` folder is not on the repo, seems missing https://github.com/DNACodeStudios/react-rails-bootstrap/blob/78a4f3aaee24278ce4b6d6e5f98240824231f389/client/src/App.jsx#L7

Maybe you forgot to add it?

**Comment by dphaener** [comment]
@k7k0 Fixed by https://github.com/DNACodeStudios/react-rails-bootstrap/commit/e8fbc9a8bea132e27981d68e7fe51409beca31ac. It was the other way around actually. I forgot to REMOVE the reference to the Navigation component.
